Setting configs
AsPulse/lesskey pull request #19
Opened 2023-02-08 20:07 UTC by neverclear86

かんたんにコンフィグファイルを作りました

開発用のコマンドは `deno task dev --token ...`とすることで起動します(監視付き)

2023-02-08 20:46 UTC, neverclear86 commented
お誕生日おめでとうございます🎉

2023-02-08 23:41 UTC, AsPulse requested changes
コントリビュートとお祝いをありがとうございます...!

2023-02-08 23:41 UTC, AsPulse commented on .gitignore
> +.vscode
これら２つのファイルはコミットされているべきだと思います
```suggestion
```

2023-02-08 23:41 UTC, AsPulse commented on deno.jsonc
> +}
```suggestion
}

```
末尾に改行をお願いします！

2023-02-09 01:07 UTC, neverclear86 commented on .gitignore
> +.vscode
vimしか使わない派閥の可能性があり一応入れてました
vscodeの設定も一緒にコミットしますね

2023-02-09 01:10 UTC, AsPulse commented on .gitignore
> +.vscode
~~割とNeovim過激派はコントリビューターに多いですね~~
エディタ問わず参加できるリポジトリがOSSとしてはいいと思ってるのでありがたいです..>!

2023-02-09 01:27 UTC, AsPulse approved these changes
LGTM! にゃぁお

2023-02-09 01:28 UTC, merged